# Название workflow
name: qa guru diploma
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

  #Сами джобы
jobs:
  #название джобы
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      #делаем чекаут кода
      - uses: actions/checkout@v4      
      - uses: actions/setup-node@v4
        with:
         node-version: lts/*        
      - name: install npm
        run: npm ci
      - name: install pw
        run: npx playwright install --with-deps 
      - name: test
        run: npm run test
        
#cохраняем отчет pw/allure
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 3
          
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Create report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history